### ISSUE TITLE
Multiple package installations in a single call

### ISSUE THREAD

**Issue by dinckelman** [electric-package-manager/electric#15]
**Is your feature request related to a problem? Please describe.**
As of 1.0-stable, it does not seem possible to request installation for several packages at the same time. For example `electric install nodejs python neovim git` will throw the `Got unexpected extra arguments` error, instead of installing the 4 requested packages consecutively.

**Describe the solution you'd like**
Would be super handy of the installer could loop through all the requested packages, and execute an appropriate function based on availability

**Describe alternatives you've considered**
No alternatives available in Electric

**Comment by XtremeDevX** [comment]
@dinckelman to simplify parsing, instead of spaces, we use `,` so it would be

`electric install nodejs,python,neovim,git`

**Comment by XtremeDevX** [comment]
Electric will do this in a multi-threaded fashion, we don't claim to be fast for no reason 😁
